/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_DROPDOWN_0 (GUI_ID_USER + 0x02)
#define ID_DROPDOWN_1 (GUI_ID_USER + 0x03)
#define ID_TEXT_0 (GUI_ID_USER + 0x06)
#define ID_TEXT_1 (GUI_ID_USER + 0x07)
#define ID_TEXT_2 (GUI_ID_USER + 0x08)
#define ID_TEXT_3 (GUI_ID_USER + 0x09)
#define ID_TEXT_4 (GUI_ID_USER + 0x0A)
#define ID_TEXT_5 (GUI_ID_USER + 0x0B)
#define ID_TEXT_6 (GUI_ID_USER + 0x0C)
#define ID_TEXT_7 (GUI_ID_USER + 0x0D)
#define ID_TEXT_8 (GUI_ID_USER + 0x0E)
#define ID_TEXT_9 (GUI_ID_USER + 0x0F)
#define ID_TEXT_10 (GUI_ID_USER + 0x10)
#define ID_TEXT_11 (GUI_ID_USER + 0x11)
#define ID_TEXT_12 (GUI_ID_USER + 0x12)
#define ID_TEXT_13 (GUI_ID_USER + 0x13)
#define ID_TEXT_14 (GUI_ID_USER + 0x14)
#define ID_TEXT_15 (GUI_ID_USER + 0x15)
#define ID_TEXT_16 (GUI_ID_USER + 0x16)
#define ID_TEXT_17 (GUI_ID_USER + 0x17)
#define ID_TEXT_18 (GUI_ID_USER + 0x18)
#define ID_TEXT_19 (GUI_ID_USER + 0x19)
#define ID_TEXT_20 (GUI_ID_USER + 0x1A)
#define ID_TEXT_21 (GUI_ID_USER + 0x1B)
#define ID_TEXT_22 (GUI_ID_USER + 0x1C)
#define ID_TEXT_23 (GUI_ID_USER + 0x1D)
#define ID_TEXT_24 (GUI_ID_USER + 0x1E)
#define ID_TEXT_25 (GUI_ID_USER + 0x1F)
#define ID_TEXT_26 (GUI_ID_USER + 0x20)
#define ID_TEXT_27 (GUI_ID_USER + 0x21)
#define ID_TEXT_28 (GUI_ID_USER + 0x22)
#define ID_TEXT_29 (GUI_ID_USER + 0x23)
#define ID_TEXT_30 (GUI_ID_USER + 0x24)
#define ID_TEXT_31 (GUI_ID_USER + 0x25)
#define ID_TEXT_32 (GUI_ID_USER + 0x26)
#define ID_TEXT_33 (GUI_ID_USER + 0x27)
#define ID_TEXT_34 (GUI_ID_USER + 0x28)
#define ID_TEXT_35 (GUI_ID_USER + 0x29)
#define ID_TEXT_36 (GUI_ID_USER + 0x2A)
#define ID_TEXT_37 (GUI_ID_USER + 0x2B)
#define ID_TEXT_38 (GUI_ID_USER + 0x2C)
#define ID_TEXT_39 (GUI_ID_USER + 0x2D)
#define ID_TEXT_40 (GUI_ID_USER + 0x2E)
#define ID_TEXT_41 (GUI_ID_USER + 0x2F)
#define ID_TEXT_42 (GUI_ID_USER + 0x30)
#define ID_TEXT_43 (GUI_ID_USER + 0x31)
#define ID_TEXT_44 (GUI_ID_USER + 0x32)
#define ID_TEXT_45 (GUI_ID_USER + 0x34)
#define ID_TEXT_46 (GUI_ID_USER + 0x35)
#define ID_TEXT_47 (GUI_ID_USER + 0x36)
#define ID_TEXT_48 (GUI_ID_USER + 0x37)
#define ID_TEXT_49 (GUI_ID_USER + 0x38)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "", ID_FRAMEWIN_0, 60, 20, 350, 205, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Cancel", ID_BUTTON_0, 30, 158, 50, 30, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 149, 167, 80, 18, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_1, 249, 167, 60, 18, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Tue", ID_TEXT_0, 88, 15, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Mon", ID_TEXT_1, 53, 15, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Wed", ID_TEXT_2, 123, 15, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Thu", ID_TEXT_3, 158, 15, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Fri", ID_TEXT_4, 193, 15, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Sat", ID_TEXT_5, 228, 15, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Sun", ID_TEXT_6, 263, 15, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "1", ID_TEXT_7, 53, 35, 34, 19, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "2", ID_TEXT_8, 88, 35, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "3", ID_TEXT_9, 123, 35, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "4", ID_TEXT_10, 158, 35, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "5", ID_TEXT_11, 193, 35, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "6", ID_TEXT_12, 228, 35, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "7", ID_TEXT_13, 263, 35, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "8", ID_TEXT_14, 53, 55, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "9", ID_TEXT_15, 88, 55, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "10", ID_TEXT_16, 123, 55, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "11", ID_TEXT_17, 158, 55, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "12", ID_TEXT_18, 193, 55, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "13", ID_TEXT_19, 228, 55, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "14", ID_TEXT_20, 263, 55, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "15", ID_TEXT_21, 53, 75, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "16", ID_TEXT_22, 88, 75, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "17", ID_TEXT_23, 123, 75, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "18", ID_TEXT_24, 158, 75, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "19", ID_TEXT_25, 193, 75, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "20", ID_TEXT_26, 228, 75, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "21", ID_TEXT_27, 263, 75, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "22", ID_TEXT_28, 53, 95, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "23", ID_TEXT_29, 88, 95, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "24", ID_TEXT_30, 123, 95, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "25", ID_TEXT_31, 158, 95, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "26", ID_TEXT_32, 193, 95, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "27", ID_TEXT_33, 228, 95, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "28", ID_TEXT_34, 263, 95, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "29", ID_TEXT_35, 53, 115, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "30", ID_TEXT_36, 88, 115, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "31", ID_TEXT_37, 123, 115, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "32", ID_TEXT_38, 158, 115, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "33", ID_TEXT_39, 193, 115, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "34", ID_TEXT_40, 228, 115, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "35", ID_TEXT_41, 263, 115, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "36", ID_TEXT_42, 53, 135, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "37", ID_TEXT_43, 88, 135, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "38", ID_TEXT_44, 123, 135, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "39", ID_TEXT_45, 158, 135, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "40", ID_TEXT_46, 193, 135, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "41", ID_TEXT_47, 228, 135, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "42", ID_TEXT_48, 263, 135, 34, 19, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "|-----Calend-----|", ID_TEXT_49, 0, 0, 340, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of ''
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItem, 2);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetFont(hItem, GUI_FONT_13B_ASCII);
    FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    //
    // Initialization of 'Cancel'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_13B_ASCII);
    //
    // Initialization of 'Dropdown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_SetListHeight(hItem, 30);
    DROPDOWN_SetFont(hItem, GUI_FONT_13B_ASCII);
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    DROPDOWN_AddString(hItem, "Item");
    //
    // Initialization of 'Dropdown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
    DROPDOWN_SetListHeight(hItem, 30);
    DROPDOWN_SetFont(hItem, GUI_FONT_13B_ASCII);
    DROPDOWN_AddString(hItem, "01");
    DROPDOWN_AddString(hItem, "02");
    DROPDOWN_AddString(hItem, "03");
    DROPDOWN_AddString(hItem, "04");
    DROPDOWN_AddString(hItem, "05");
    DROPDOWN_AddString(hItem, "06");
    DROPDOWN_AddString(hItem, "07");
    DROPDOWN_AddString(hItem, "08");
    DROPDOWN_AddString(hItem, "09");
    DROPDOWN_AddString(hItem, "10");
    DROPDOWN_AddString(hItem, "11");
    DROPDOWN_AddString(hItem, "12");
    //
    // Initialization of 'Tue'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Mon'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Wed'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Thu'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Fri'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Sat'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Sun'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '10'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '11'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '12'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '13'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '14'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '15'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_21);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '16'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_22);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '17'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_23);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '18'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_24);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '19'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_25);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '20'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_26);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '21'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_27);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '22'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_28);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '23'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_29);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '24'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_30);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '25'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_31);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '26'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_32);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '27'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_33);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '28'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_34);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '29'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_35);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '30'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_36);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    //
    // Initialization of '31'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_37);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '32'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_38);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '33'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_39);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '34'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_40);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '35'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_41);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '36'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_42);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '37'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_43);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '38'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_44);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '39'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_45);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '40'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_46);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '41'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_47);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '42'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_48);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '|-----Calend-----|'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_49);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF8080));
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Cancel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_1: // Notifications sent by 'Dropdown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Create
*/
WM_HWIN Create(void);
WM_HWIN Create(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
