/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0        (GUI_ID_USER + 0x00)
#define ID_TEXT_0        (GUI_ID_USER + 0x02)
#define ID_TEXT_1        (GUI_ID_USER + 0x03)
#define ID_TEXT_2        (GUI_ID_USER + 0x04)
#define ID_TEXT_3        (GUI_ID_USER + 0x05)
#define ID_TEXT_4        (GUI_ID_USER + 0x06)
#define ID_TEXT_5        (GUI_ID_USER + 0x07)
#define ID_TEXT_6        (GUI_ID_USER + 0x0A)
#define ID_TEXT_7        (GUI_ID_USER + 0x0B)
#define ID_TEXT_8        (GUI_ID_USER + 0x0C)
#define ID_TEXT_9        (GUI_ID_USER + 0x0E)
#define ID_TEXT_10        (GUI_ID_USER + 0x0F)
#define ID_TEXT_11        (GUI_ID_USER + 0x10)
#define ID_TEXT_12        (GUI_ID_USER + 0x11)
#define ID_TEXT_13        (GUI_ID_USER + 0x12)
#define ID_TEXT_14        (GUI_ID_USER + 0x13)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "", ID_FRAMEWIN_0, 136, 43, 480, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "23", ID_TEXT_0, 43, 20, 110, 120, 0, 0x0, 0 },
  { TEXT_CreateIndirect, ".", ID_TEXT_1, 158, 53, 22, 22, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "59", ID_TEXT_2, 185, 20, 110, 120, 0, 0x0, 0 },
  { TEXT_CreateIndirect, ".", ID_TEXT_3, 158, 85, 22, 22, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "59", ID_TEXT_4, 327, 20, 110, 120, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Year                 Month                 Day", ID_TEXT_5, 121, 130, 240, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "2022", ID_TEXT_6, 118, 152, 50, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "12", ID_TEXT_7, 219, 152, 50, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "30", ID_TEXT_8, 319, 152, 50, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Temp", ID_TEXT_9, 21, 199, 50, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "30.9", ID_TEXT_10, 29, 220, 35, 35, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Simplicity", ID_TEXT_11, 140, 195, 200, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, ".", ID_TEXT_12, 300, 53, 22, 22, 0, 0x0, 0 },
  { TEXT_CreateIndirect, ".", ID_TEXT_13, 300, 85, 22, 22, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Alarm", ID_TEXT_14, 399, 199, 50, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of ''
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItem, 1);
    //
    // Initialization of '23'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '.'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '59'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    //
    // Initialization of '.'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '59'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    //
    // Initialization of 'Year                 Month                 Day'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '2022'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '12'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '30'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Temp'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of '30.9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Simplicity'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FF8080));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Alarm'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Create
*/
WM_HWIN Create(void);
WM_HWIN Create(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
